--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mike/gruvbox_coloredChina.png"

-- Special
background="#121d1f"
foreground="#f3c187"
cursor="#f3c187"

-- Colors
color0="#121d1f"
color1="#DC3326"
color2="#DE5E28"
color3="#F64632"
color4="#994A57"
color5="#69926F"
color6="#BD9F2F"
color7="#f3c187"
color8="#aa875e"
color9="#DC3326"
color10="#DE5E28"
color11="#F64632"
color12="#994A57"
color13="#69926F"
color14="#BD9F2F"
color15="#f3c187"
