# Shell variables
# Generated by 'wal'
wallpaper='/home/mike/gruvbox_coloredChina.png'

# Special
background='#121d1f'
foreground='#f3c187'
cursor='#f3c187'

# Colors
color0='#121d1f'
color1='#DC3326'
color2='#DE5E28'
color3='#F64632'
color4='#994A57'
color5='#69926F'
color6='#BD9F2F'
color7='#f3c187'
color8='#aa875e'
color9='#DC3326'
color10='#DE5E28'
color11='#F64632'
color12='#994A57'
color13='#69926F'
color14='#BD9F2F'
color15='#f3c187'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
